apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Dev environment: override namespace, use standard Deployment (no Rollout patch)
# No need for Blue/Green in dev, fast deploy for testing
namespace: boutique-dev

images:
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend
    newTag: v0.10.4
