---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB7IjQbgmsvnRZD1Odsvafw0tDImL8Mgu/I7p7zF4B6/f5PBcDSh+9xosCeYAAcj5/Us/ZLp/bgq/qLr9TMDHDV8Au26zo6YSbOxH8UXA/7G77kq+Uybq3rSF39Mem9J5ducuhU6agnore+4LCA1fN/f++zoS+G7ayHCu9rnQVvsVrbk0zHU7jql+yUWWjT3tXk5hp32bJrDc5HJN482DXlisKHWRkG7HUHgCqLJQkRQ5MBvh3ZQU4xOv2kwa8TsMl30hSGYcBfwfp7YU+7vIPKHz7PbVW7OqFqBcGniCEIJlG/CGKIV/JL/s8jKNfjykb8gCsmabMCJvz3Z8WRu74wGJFabhm0Zv/GA1UpFO6owLnZ5Xl7kKVlNrgnRqXDwy/1//Ry8Kt2lbfmawfwPjKasFOWuSUzOarO9ehyiMrmjEArMcbFvyXtWkL1q3j7Mv+bIepmfdacGJZmve6xJZcPHlqGL4TIT3I9H+cuUtGuEO2l6/yZNmaCrhZIDvGlvifc/rVJO6B633uXUtjn9BllD0y19EhHI5jgKN+z/NC2Or3/DsPyLD6mz/nMZe8x2xKYbmod0XFReRqP1AQ6I21ehKDSqhqPw3rutyvfhgIO2f8P7iYJ6wOvPjlXkKnBqIasbcTMZ9VvH1Ntc/s40WvQPK456BEk20c1RkvAxqBpicx5sC4AJQJ6eG66EeneUdB4
    admin-user: AgB7STY/7mC+UhzqeXWmAD1hj9XkEeUDP1rch/APT7rpR++xrNNvoVFc+kdJDGk7L9l0RV7/7A3NPskCJwDAFOraw71nvzELHT23TUljwzM6MM8bhkfAI4B7QXWsUu+F067mdSkiXSgn0HmZ+sVDzVTw3zsRKk67iriWcdSuwzdDzqualdzdP4PZbhlbZVEmtiP88UWZQrrJq2umsmJFOBZc7crCtxtZIO59dX9LRhck61/w9TPuPxcPB8Kj76KvGgNwsX1PjJf9ftbTNvhF8hBEvRRA5SgNWJPciO9Y1lgBnFoANdhmb2Y0rHSogldcckV1jJvPYsndxnmbbHtDVJv4Xxdmx3gg0yk1OQAoiz9YkwOdIRLRUNHBV+vN7uL/wkb6b9mx7vAmfLsH+45raVHyb5Min5tsQVXFpDxlXy168cIG69Eu8bvNwXnowaD1FWlhsOlCdFHXgpoRpKd5Pn1ld0kfnjzF57dwUmQZ+E8v3cRM6xaBJ0N5CkUcCQA3YJjil2/iTw6+mekVdbbAKstjl88/3rz2TKPvfvQLcorVGqoE5Mdvt7/GCpDD4XHd5OGRfU30ubUrRiYBArYi8jkaw7EdD/Xs+q8ocViveM4IbhpOg3zYrIfm7cK3s7TM5LaEdtTTQvsh9Ihkw+ShrLN2Fb5Yx8YgPwozi3Gu9idpDeBUCKw6yzEtFLtrIp1wBRB4T3bRRw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
