---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgC8pJOCh3Hpr15mSH5TvhYLs6yXVFDk+rQxLgedwp2/1mMUsWJZUwRiddr06qZuyx0HKEiNC/RrRuWii8buWpU6w0Pz+0W8+Q2ijbNDykSufTENVGafN8/5J4o8hTLoyr2xiGTmaUCKYD4V6tS3rtoDXPrcbR9V872CvQAbyku963Ux+m1ef15Fwq2CY2LPmqnjlA2VPBu3rgx6hq2rLECUbXrGtobO3+KdrdYf1J6wlPbi3kwvYMXafLmGYQFJYzRLY4x6y/qyq2GeWvBEOSVqlmLwKau2TOdBbquOCE1NpexZvtFv8u9KJIScE1vy5mNfq4i0G9bfkUVzlNrZ7XrCl/7hKEQtHEppmywNC004h2thMqRhZWncLNEJNvcNNLKMBM/oYphtpISbxKH+RoPHyBscHzYs2h2qmD9LmdaAody8pQ7b5ORxFNkOrbWuTWER7OA2BOBD3UB0Eq9nEyo47hJvvqE8CBZT5TQ9DtX70pv3UpU69oaIIyC30QLXmoqE6J1fja9+EbXolfhVJQe9QNdxVrZsgKqEBXjIFMe3WJTRZIBn40O1q12YdU7j1MOKwD2TUJ/jcDUgn1UU6g1GbuLc2poECR7PMEm2z82qD/8gRQufKmvVEHSrp9UN6RlaHBf81Vyh8/XF3piMUF1duf1xQ4v5RyB9nj8ieTUSQmSsFUz90Gb3q353wgkSifY=
    admin-user: AgBCUU1ujVhmEo0YDx4dE22dqymr546qiPAYYhRj+wI3WQjVkNz8mfsV+j35uaD1P/TMH9BzVSXKNeKa5IXPY0FO/QM8vbrJiWA0WmP6Xza710HvXVQTREeLeF3EEKGt/aMrOkf3xpnaiLBcl3R9tmgiHBq/j5S+lxpC3VjGgA1UEyTIPBl7NyiYkTP1MF79ynr/Bcc2hKgSH1ba5ZQA4AT/7R3xAHBxR0yICr7gOlAufYyhjqluTvrK1dR3vaOJfU71M0WsEuEBrXZLSLC8WZy+ukzgNkI2Lqqb/U+UQx41YYaqwvvGaTDlTC+5FP/+HzB8jP/l0jgt5rUVpM+xVRi7NGq8QdbUChc4vpTrHENoDwp6Zz4oyUWsmrFdAcg6yRDdifiRWEBzKiU2Lhc2ved3s7xw7YPrelcf712q0T34KuBsmaaefIhq5TrDbwUta3TkzD9nmsRZuEviBFYIWDuIBHe3iIkoGRfEx17Ift0UKfvQdCcYPrCpSG6frPVlGLhqyoR/l2lRzM/ruB8zQH2frcmJDK82D7nTI9fB96rFpG0fJfqfXsRXoyH8F4vWJhMncl5OgmGxSXpVlHXH0vc9ZM5oP0No7ZX2IMFE3ofzM+UH6zknSVrn8vyIobnYDebFDhra1CYMJy+seh51uT89cFIoOOFG+TK7HwlmNpVkR6Jo/UJeF6V0fye8/ExL/iSNFZar/A==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
