---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBkVv3N/o9anJaBRXwtAXrhhlJ3Q6c/wm1ts0B/SeubgIqaXRX59hNZ1vc5AknIGfa3P4EmLNrnGxArVzpnqgtj7s5lCMe7eqyITWvBMAAkQOcjknk/pS+4ruusy2045FaVYRX/w23a4U0ELxVJ6SDCRqZ+qWJ32UrSeUud9Abj4keD3bFq6iGTwRLKmAzlK7ZQ13kF1Jh36GpArYeN/vMUbX2m5erGgNHptnUOhj+l+G388et3tRc5SkEdV3Q9o35fjqUuniQtPf+hrFQKrs7Zrp1/TNadhtXEs/q/0q6aGgdgusFAvgVKVttIYFlCEAqfOyQjYRQC5iFkC7f0Mkdzki8uhEIIQkZTazIjYFZ+1LYTRrqqjesau+bHZO64eZ3TjEQ8eFSZc3Qcz5pjFSXjmPNeJFYoVde13gDROm0mFLPK9GaRlmVNE2gq7ZbeP0YclikRQ0yY92qSN98sY/jX+1g9UcVNFcshWgG+N9Q8hH/xUinlRy/KWUMuKNMlCau9QcnVMciD6R4ZFfokcZ9qcHkUzMupPJK5JObocdU+6UoAeRrfusA1gMXwzOe9j+NkpXNsOoheKMwZtIjF71xFT6rSJhn3P0hHMhifi4qJIDqoHQT3m0prDD5DE+CZ7BCD2PgYOwAvNvMChZEUtMYCcu1XdkbenGGlv5jWKv4Uuo4uOkOM4g1q3qYAThHwreOe
    admin-user: AgAZurSFdIl9TWjGo1lPiLKZiz6vQXV0AP8ivgJLcPJNBfNte1unBa1iVZSCxXOooBnY9ixJd0NXLJMHUJqG74oZYqH0SETglnq9edhs2UXhAXMFQLjlU9T+1sDi/SRzoAgQYtEUbcCDrxpnh77mxt/hbdDfXlWiIaj5NNsxZifd9I0VzTDjolbvxdCRF3Z0vj1d/rCouxbarVe+HcLU2mK3VbhP7k7mcNAr6WG08HVJsx5rWZsoIiJuwBpPH1fBA+fmbh4dWFQYloLEmlU/06L7PinzivHqd7TLGXXlGkaFV1JWEdKm/gtroBVcRe64JP5YGGui/3aFSlZp09zueInla/8a9l4VaSuyDLWjF8pm4oSWSPB9g/IZsRw8FTBF9vYiLw/wsQYBp/nS2S3EBk82YNHV/SBAJ7tbEBtla259PjLuPzweZHZNJAE9CGp2ydQAaHeDypViKi/K6s3ilK59M+qsDayM1mXNQNnotowGuGtT8tizrO/BIvo28JN9pXRRKrSMP2MSZqZhSwBE9qyrngGtFW1pETkPMdtdqQGyH6ihorN1T/XFn8qme3upIGi9LiiSWyatyKW5mQfntWicnEy9evd0jRWl3IQXJBxrVgnocX7z7frJROflD4ljxmMjU4a3V0N9ruL3OYhGapqijy/7LYxv4U0ebJHjZ0pf7PIhoCEQxnVGPkfZ7MuT+WN8wCxGBw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
