---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-slack-secret
  namespace: monitoring
spec:
  encryptedData:
    slack-webhook-url: AgDYjg9uskGD3YaXL4ozT+zb4hgTKevbA4GEqMy2JdFTNqGHqsjlc8xF5pQlbihZYaex0og732zNOTSkcKHVFA43zxhHMeCda5DNzhGrf6HATvOpbD3PmQnm2HVLTAAMmuOHdYGb6eArPT8lxK3IJ+rp31Uufl2FW+/CJMZ2ziZgCtIYU92I8xg1dCY7cBkepb3zVJP9uqCSHH9y6Hc5x0zK4JF8bbyj4O6GNSdEOK8HyMfgv/wz9QLTPyegv7rKll8c+hI4KdCQiukrGJTY0OUZoBwqhLga9m3/pEJ31W/0nWhMkvLKqo0RIDmq7KUtierPoUyn5hYV+dILw0Uo6+9Amq+9vPC3BKbCkeQjuvKkLhPhgpelP7oH9DYG8cyPoTdpBR9OXpyHZintcvpLWMLrd6JkPpQJFJ1Ryd8sVYxdjtb3NgdEefl1LTGFbMRwneQRvSemIislvaPGOk+EovrZEgCyLoe3vc+fgZ8i+2CFKpQm0PutNlqdWdoL0c84Eyb96sXRRC088bQuWcDRTc07ZUQ0daC77Af1QPrwL4hKIHNSZhq4ZRnS57Fr/CvIyn6Ct96XzP8oKvjMsMd/Be/cs1rsEtz+1IP9I6g71z+RXuSmDqBAwX7yjIgM9b6P5D7TKjOy5S6I7025zZ5ZMFOa6I9WRjyhSTqcGYeUwRooo7i+4j1SGC7bklV7ujy12PI40kjzG/e6Lg0k8b8TvIzsMGj5Fq6NdBTEcZZM1LVcMsJmRfK6I4YsS0EOlx3uZhd0PQbSa4+HBQ+CWIbVITVNAZltWCSFC71TQ+lm4fRM/lQ=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-slack-secret
      namespace: monitoring
