---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-slack-secret
  namespace: monitoring
spec:
  encryptedData:
    slack-webhook-url: AgC9OLbiaagg5Y1vuNV5hWmyOLZuPvDhI83tfLHmQ93ByV+ojP3LevKmDPjaaRafswEja6EbBaWDOcG+QPRSLNk4ELdBsdXXGhgM54Et+Ud3Get8+j2ERTru503xAV/jqjlBI61FjiUg44Hx8aFxIR2KSd3DmzcrdywhbYtYnUZL8k8ICM4FWVhCnIzwRo57p3SUKOyA4hVvD7tZ/y4dVbNPeSba3gCDadT7CuWKMj2uRauz4o0KwkHxdGTyn1C/mcKdiUrrd9rPJA7CiYCB/yWeNsVaSaCRDRgwG+SR8BZ/UWnQUajczpbtsS1cN4am2beMVVywwuBEI6jzFHREEKyWsz0BQnpfttwSztlnslZiYvnGO9nHWgPr3SggGchApdCwYtmwXbbq+sG4URibbouFUkwFqkQAyuL68MAjjn6WoijSbx3vHqkSS4AsEb++o2Ug4kVWkY59cfAMIJPfDiiw3vWinqCxoHzaxJ5ZX57VW9ZmTlErFSkdvsbIXYK7dChIFlZT/IALtZCS2YJmVrVtRZ57XhUQ3rGbWLSR31xM7Vt6eB1Fw/P83w1+WeH5GtIndInq237Rh5va2rQPueVpQvoFznZjYPp+naYAcqAuhfw/LXC0URJprtcysIkyAZ9V98E4M3byEPGiTuxWSycaBz1wETbJdrE7GX2BCThsdll9CQelo7cLXeLL6vMzvPeIhNFXOfYF5RqnlkGvVl5PI5waHl2JqkI3mDtxIqCblFN0TDEUcFQHvoYsO2K7fuiPwtwfR9yaVLGWJnQfh+8oeQScMWfkx6u+hIdSQ+5ytiw=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-slack-secret
      namespace: monitoring
