---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-slack-secret
  namespace: monitoring
spec:
  encryptedData:
    slack-webhook-url: AgCxFAdusSXXl5ppF4qhZ3CLEvkw6nMWQ+GDqqoMGU+d1n/r/mRb+Xe4Dx84EELamm1yNReaB/NIusLkOb9hPo+JocLw3lQ4m5geKiS6Aip7GjGZmMftY93k2mLn2A3HRGjzd7zzfZG6UXrm4WOmmRHgsIIAKixo5TasQf+ut5D/nFDhhKAnvBnjTWwtq91ysjE2HU5RQCGHOPOVpRTrA1twwa7vPT9aCwhntcQABReRCSKB+NdKFZQCLkPpX7wdvqDtlRo1tIogOQHB7nAufcn86EL+yhg/F1MWE5hPCL+MkLx6nVpXib2PjJZHYAIDPWXzUluWiwN0kQg834X7tXjnDaXNz0Vi5fV9fYnRT+r9a49llTU5jV803TQrj5ZtbfZY1LgI5zh92mvPtRKqaJA5PPMbffiQMRmLLejdt0aSQiLM97U7g5uAjdysMHpvVdD8m35oeiIkhFzIqOtjhrC5VUrOu4e/4yfiITGOy/ezn6lcxTcwsxD2kLfKvhnzBWlqi4j+zU4LLnlqTTpiTb8zfqtnRQMR61D6t4doBiEx1OFuz9ER3lXkMk0bGBWgAsC44+FYCBa+mqPX0B8+h+z/st5YvlNjsmUyh9q9V4OiYpweDPrM091AYrSm2Bx7UzYen9Cp1wZ0niGJvIe5ZWuLElX4JNjxWaEVflfisxlibvZlLC2XtO3Ylrb6RMgutpeqLN+XHFK/UCnQXS1rSDu4anzCNb8/S+Yd2TIfbrPiwk2mTtGs0Xk2UsVxurC+gHka+MfR6LwFswfztuQReo0O/nw+KChCLh5Yk21RX2gRKFU=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-slack-secret
      namespace: monitoring
