apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-monitor
  namespace: boutique
  labels:
    release: monitoring-stack 
spec:
  selector:
    matchLabels:
      app: frontend
  namespaceSelector:
    matchNames:
      - boutique
  endpoints:
    - port: http
      path: /metrics
