apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: boutique

images:
- name: ghcr.io/hmdat-1706/proactive-scaling-microservices/ai-prophet
  newName: ghcr.io/hmdat-1706/proactive-scaling-microservices/ai-prophet
  newTag: main-50b72611c72daf7c2a10e6a2688fc4ad30959208
