apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: boutique

images:
- name: ghcr.io/hmdat-1706/proactive-scaling-microservices/ai-prophet
  newName: ghcr.io/hmdat-1706/proactive-scaling-microservices/ai-prophet
  newTag: main-4e3f21853c657b5a8e8c911223d01707acaaed5c
