# 1. TẠO Ổ CỨNG CHUNG (Để Thợ rèn và Lính gác giao tiếp)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-model-pvc
  namespace: boutique
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi # Chỉ cần 100MB là quá dư xài cho file JSON

---
# 2. THỢ RÈN (AI Trainer - Chạy định kỳ)
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ai-trainer-cronjob
  namespace: boutique
spec:
  schedule: "*/5 * * * *" # TRICK: Cho chạy mỗi 5 phút để bảo vệ ĐACN cho lẹ, thực tế là "0 * * * *" (mỗi 1 giờ)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ai-trainer
            image: hmdat-1706/proactive-scaler:v7
            imagePullPolicy: IfNotPresent # Cực kỳ quan trọng: Lấy Image ở Local chứ không tải từ mạng
            command: ["python", "ai_trainer.py"]
            volumeMounts:
            - name: model-storage
              mountPath: /shared-data
          restartPolicy: OnFailure
          volumes:
          - name: model-storage
            persistentVolumeClaim:
              claimName: ai-model-pvc

---
# 3. LÍNH GÁC (AI Server - Trạm phát sóng 24/7)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-server-deployment
  namespace: boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-server
  template:
    metadata:
      labels:
        app: ai-server
    spec:
      containers:
      - name: ai-server
        image: hmdat-1706/proactive-scaler:v7
        imagePullPolicy: IfNotPresent
        command: ["python", "ai_server.py"]
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: model-storage
          mountPath: /shared-data
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: ai-model-pvc

---
# 4. ĐỊA CHỈ MẠNG (Service - Để KEDA biết đường tìm đến)
apiVersion: v1
kind: Service
metadata:
  name: ai-server-service
  namespace: boutique
spec:
  ports:
  - port: 8000
    targetPort: 8000
    name: metrics
  selector:
    app: ai-server
