apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: boutique-dev
images:
- name: ghcr.io/hmdat-1706/proactive-scaling-microservices/ai-prophet
  newName: ghcr.io/hmdat-1706/proactive-scaling-microservices/ai-prophet
  newTag: dev-f93707bcf8a0fea132fa36c99d73f76fd923dd29
