apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: boutique-dev
images:
- name: ghcr.io/hmdat-1706/proactive-scaling-microservices/ai-prophet
  newName: ghcr.io/hmdat-1706/proactive-scaling-microservices/ai-prophet
  newTag: dev-3a99004426c245a6d9b47efca274a9acef73601c
