---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-password
  namespace: boutique
spec:
  encryptedData:
    redis-password: AgAQw/k3XuDcv0RdYLgCC02GdIV4Ntn8gICMXcP3c1JDUqZ48G/l68xVOt7W8Ujl7OHkrI/BrK0ntID3M0i+XUWaZPn1LtXdznQ3XSfjhX+RSqyTPkvgVM+raLoBx4kuITMfZ/zjCdo24SH/qmlYUoshAvLGnVXyaKYKttlVdfmIZFfW9YRjPZ3CZK1UXnc0dN2TtkslSKvwx5Q+0GgMCbFBWyp3ipH3WHVwocvk4JtlsDHwHljNb9j9swPaHGDch5dAFS8/bVeFZ20/RmLliFTuBB41FrmRPh3lmQpdakya4n/CaXP91ASIeQ16Pkfso6vAYEu63WsohT76+KiRjHyLa0qJlS1lFIHOcCOGDeRz3wqQ4ZNoaFf6V93F7AnhN/DiR8jKyeTpEVHR627w5dq/vErsxt8pdpSVDb7bEtIBILBe7HvwjXSIbuARSz5+eKoLQ+tql29h5IvRoLHHqTTg2egBJuU+Y3NOraHqJyspJgyshCNoCsDJNXxZW2jAYRS9XFHxA7abYO3P3bRXh1LG7pCGBQeHLFfsOQr9hobdRh8En090sCaidZDJaP/CAWfAvMwGwGuYGFBIAJqGzdGtT49GVhadOhEtKj0eCM1teQ8vKdVygey2a/vbb8ZoSxfQgJTanyTB3Xoai8FQxg0JJbysaDC6PtvBKwgAt+azBCpBvqn0muhAQcwNyBfxmqnLLK8xcT7yKg==
  template:
    metadata:
      creationTimestamp: null
      name: redis-password
      namespace: boutique
