apiVersion: v1
kind: Service
metadata:
  name: mimir
  namespace: monitoring
spec:
  ports:
  - port: 9009
    targetPort: 9009
  selector:
    app: mimir
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir
  template:
    metadata:
      labels:
        app: mimir
    spec:
      containers:
      - name: mimir
        image: grafana/mimir:latest
        args:
        - "-config.file=/etc/mimir/mimir.yaml"
        ports:
        - containerPort: 9009
