apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: currency-scale
  namespace: boutique
spec:
  scaleTargetRef:
    name: currencyservice
  cooldownPeriod: 180
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "80"
