apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: currency-scale
  namespace: boutique
spec:
  scaleTargetRef:
    name: currencyservice
  cooldownPeriod: 180
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: metrics-api
      metadata:
        url: "http://ai-server-service.boutique.svc.cluster.local:8000/api/forecast"
        valueLocation: "predicted_rps"
        targetValue: "100"
    - type: cpu
      metricType: Utilization
      metadata:
        value: "80"
