apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: email-scale
  namespace: boutique
spec:
  scaleTargetRef:
    name: emailservice
  cooldownPeriod: 180
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "80"
