#Scale Frontend
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: frontend-proactive-scaler
  namespace: boutique
spec:
  scaleTargetRef:
    name: frontend 
  pollingInterval: 30
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: metrics-api
    metadata:
      url: "http://ai-server-service.boutique.svc.cluster.local:8000/api/forecast"
      valueLocation: "predicted_rps"
      targetValue: "65"
  - type: cpu
    metricType: Utilization
    metadata:
      value: "80"
---
#Scale Cart Service
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cart-reactive-scaler
  namespace: boutique
spec:
  scaleTargetRef:
    name: cartservice
  cooldownPeriod: 180
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "80"
---
#Scale Product Catalog
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: productcatalog-reactive-scaler
  namespace: boutique
spec:
  scaleTargetRef:
    name: productcatalogservice
  cooldownPeriod: 180
  minReplicaCount: 1
  maxReplicaCount: 8
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "80"
---
#Scale Recommendation Service
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: recommendation-reactive-scaler
  namespace: boutique
spec:
  scaleTargetRef:
    name: recommendationservice
  cooldownPeriod: 180
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "80"
---
#Scale Currency Service
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: currency-reactive-scaler
  namespace: boutique
spec:
  scaleTargetRef:
    name: currencyservice
  cooldownPeriod: 180
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "80"
---
#Scale Ad Service
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ad-reactive-scaler
  namespace: boutique
spec:
  scaleTargetRef:
    name: adservice
  cooldownPeriod: 180
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "80"
