---
# kustomization.yaml for autoscaling manifests
# ArgoCD uses this to apply all ScaledObjects together
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend-scaledobject.yaml
  - cart-scaledobject.yaml
  - productcatalog-scaledobject.yaml
  - currency-scaledobject.yaml
  - checkout-scaledobject.yaml
  - shipping-scaledobject.yaml
  - payment-scaledobject.yaml
  - email-scaledobject.yaml
