---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: boutique
spec:
  encryptedData:
    .dockerconfigjson: AgDGcV3/HwJ61wb5iavFwimNnG4MZWVrxbIQ7cjgFJ/sktwFAPMIxzaFXzrlkqWLR9N66tCr5SKlYjEUHc22w5Q0ixPKxN2iGjIGttVAiQeTWmns5Mt3+3YHPb/QbCTw+Y+iviekcUZ3JttSyOEN0axv4vv6LA4Ik3dt4giWnjerKbU3OPMM0qCZh1R1vKY5rzuBSwXZgNRMA7E6Xzo3l3k+zBcSWlFIaTLS+DW36d0kJjyLUMzMWp8U9ej5EMk1iCVfPucQY0OCZWgYOKWq5AS6hpJLkydRTYKVtNR7lf/LwaZLWK0K4ZNlrT/w4I5LhLS26j/kA02VFcyGpv9fUzD/ukMh+zllz+4S0RfMDcmNBQVTXmc/qBapspFD7ovc9bIbna8PJyMlUmTi6Il+jJ6pecJU+41EQ4Ll5/B6f2KDiBsD/cvJrBx8pv5HlrMV5LBct27HyfnQgt0m0GFKA6ntvZ0uIj4+ZJclrNmUn/yJQovSBdWf58weWEw0LbmEWQcPZ5iq+wxq5zjzGFz+UCLK6s7Y2MNolkJTsAsRm5bxBeiT5XIp/fGOsdMFCq0watZQqi1uOieGRA0dib/1uCWWMDjciDIhSe7OKAQJYOAz9ch3HQUR9gDrhVdYA6wJoeA37pO+5YUx1f+fmQ2RkepNEGuTDGH38a/XcMO0NSUK5+EVNR1y91DXxJ7yreYr1QArvNgyOCEVe4uPT/4RvVetc/zg2bWN2ATY1xBgNBbrgkVuPoykft4K4M7WgUCPU0UYF2T7D4pD7YDPybTfbwFz5wNMm7JOP3B95t32uvPmy+n04LtzAmEfqDdvq6PYbcT1Tize73JF9tjqV99JQkxVQHpPwlm4qUh+m2m1F1AKwVLXXu6q28UsMTYmBddIM4o1EDEzGep0xk7tPD8y/lQ54OP2Fp4ZVKK9sympIEU7vLXwPw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: boutique
    type: kubernetes.io/dockerconfigjson
