---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: boutique
spec:
  encryptedData:
    .dockerconfigjson: AgB48Mh1hd1SHHAXrvfZXqiBGFiPy0ZEtuPeKis8MMXc0GxgHMqdHzLZ3sUWuYM01nrBJzN9XiynRX6adbj5T7YoL6YoIFjds88tYXv2ZAxx0RqnEaN3kUJ2AEY7fBu/MP7qp+vH9J9FpJygbmkGFpWB7IIgIOaztK2Nq4Sek61WqVbEF9yvs2aP6ytqLiDrN/wMzkDh6CPjp1NXTXWhEo6f9Z1eOAAfwUdhf6GUFD/nEF2m6aGWop0txLvVkmiwQNPDTOqRLQbV34UywXNrHMrlTfzoWmMdqACpdwoGE6ZkxLoloK7+RpqeiydppyKhvkF/xv2i3xDE3+wDK27w0JNVUtNUs9Lk9rdliBmHO8XDF+ZRm2UkuX0Ih9udptTA6yZ+3XgmWYT80l7idwMHJusRBqyUmnjAYkBR5gM1wEjhHJZK+vfNEfY0BJNyldjx3UMag/SpQFWf1OW/gom8jnXViu4x7jlpq+YcwjA2naNUE76ka3l5mS8L2VH0SKw0lZHF2ZDDEPjRquE003fM6mE+A19ZJoEolZqQs88vyzvCq0Twq0nGJtV2WhvSdRk5xr6uwugwPRyrgbpdhPPu90qa43p1B9XuqbSVd7zO0j2MgxldE3DkmfoUXt29zbPfuM3SUawfzkDD4uh5g3HYjOtrTbnvm9sloQ43G7Nw4mylTDNbxVtKHfkSvO6LIArx2d4D57P4DZ2N3dpGOPcrs/nv5E3AviUIdmCD0IEb2d0PzOhCLRULBnd0wgaFRjQG6TXcSWQzqvNVcEsyLbmQ0CclxgcSsx6vhdrpYbcAGiJfH0edT4mFgbOtJdwGVKqjI6fNtcT2Ck9UQaF4iLdyZVYoJ37U+CwFivmW5Blufa0l36/X+6BnDxo4P9pthaoTDg29/XVFxQOCZkyJH0E/WkXscGKnBeqmfm54ENDPIFeCKFQbfA==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: boutique
    type: kubernetes.io/dockerconfigjson
