---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: boutique
spec:
  encryptedData:
    .dockerconfigjson: AgC4rUWT/rDGozrWwLuHbj7pdK6ALMqYPfV4c/ycmyrvUR6TXD5ndSH+xzQzefUE6LVTe7cUcM5oN3LBef5iCPruo316ejjex93qV2ZkEFyQ7f/bO/Km/mzfQh0A27MRBpZKWWIXmT3gK92Zpwvz9OhWBfQhF2n8DSWjVpRWsGb5Ne99WKGc8y8sSvVkhRLsev1Dvg5IdtpbldX/zQTFIRyuelaCzdBqAerJjPtSR14WCARzKbyHAVp/6pOvuZaMkbNqELPLBj8j4dsgqhXKDb4mDLgqzdHm6elBZefqSc/0GjLNrpG3fDHS5PDaUOIZgwo6y+ZyBSZYbFel/dVvA8/fNR18FWdc322A69BGLgIRnbsnHp+sJNkj+MU0mvedk0UvSr8eMY/weATBxp+NiuJCNiHUkjxGTLCWnnWbdOJV6r8jsMeT9d7J6gqgMCXJaV6Pf1Btl9NRH+YLH9GncEH1vMcLUQiJMoThlyXNwvMAJayJ88rv/5L/s4ik1Rb2L+fDBYLKCwJUUEZ4FJuWFbgMlTeKS/BXxV5FbSZ5yIwRGrnNkwvlJIej6YLidQOos5CgVD8Ci6EeDum50S2GgJsC48gv2ktHJnfHR2z0UHOf9knd4hxPB1CvxLDt/h1wI7Z/r7kwb6VJ6506uDFnbtn03LYPRwxBwjh/0lWrJWQEnZ6o5D6wmlyyYM6k6Md+GHGbQUaBxydrVEcUD9fokhfOrbMHxuRzXS9cMGFnm0dip+QwoGnLjgDZFpT+7vOpzaKH7pJ5lTfYQ/oGySA25jKggQq1P2pynnfiiPbZkBythWPh+bcrF6y64eVK2tXLsnnz4SC1A1HmiceaAQILxGrfaUHKWc8u5ZF7/t2H15wAUJWvAZ72o0AKIrGMAcnj5QBxE23sqlFW+z3xUMbTVSgean3oHOYS2rXpVToSBBBA4VbIyg==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: boutique
    type: kubernetes.io/dockerconfigjson
