---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: boutique
spec:
  encryptedData:
    .dockerconfigjson: AgAetIEtbseEmq60m1+pXcSeGYTb6a0puE32KOTuIO2e0p811xWQPakfl3i41hA0Z/xB64fRCtV68UJEWTxGJrl6NkPWECu1bALUe6BnLO9Szxxt61aCoGT8VIUCOuFfYd9Pf7Q4sdXwQoqqOlXfBr6Cau3eb07R1V+xgSNIzWTGAyQ939o+BrnQeuaYQoqG+IwMD4XMMPz6fUf1emvFTEJaLnX5+AygPVmRCfB20dzcQd6COGmc/NkH07TAIc5VZPelP8XyYtFJwUyBZFzuMd+/vygx62KuELnSd4j9n94DGa2kJ+1X3/IJNbTKto+4ntx3q6fYDDzAc2W8pa1mGrl2uXvqkeZfqQfwfXuHxLOR9eh/fZWUviIfMPwrxtxkdDRRSVYyjPC1xOyqQXYAg7jb6RjRxWPO+mSo3wYYDeudq7ZVJPvZos/nGX9RUvfs3EVvT0M9BgSdZCzCES68Xk2CdU2/fRQ7MWjeDoyG5c2yK4ZfXyoZeBmast7fZMhDIRuaYh5zwjzgshCtAcvHrhnjd9CN5gj8VsV+y5MrrnJf9kCjTPtf69Uc1yHDGo8O7P9u1Xlote0HLhyIeuLMASgqMndcdPlo0keefi888D2k3lXviJ5W1/96s+7YcorHNGOctgcf2Y9lf36YMn8+nQRMGLLHoGITCIC3QlyAoFvCpW5nmhHq/sQqs0bRLVau6v5dX/wPXJ8BblOA8wFvhd6HSAaPeCgkZ654DQRj+e/iYDJnM76OlsuG0UqRnJKfQ+A+hMR/7GDwVE3aC8gXDu3ucPKwoU5dHSE9yZtx69S9wCpAhESvqPVuH6hTl6B1VvcplnapcyAfP/68Yl7eZC/u9MAUlTBrUuouOnAntoXE2WF9TJ6jkdTOXIcqR43P9s+gPtVSU4L5H2K9U+SVqE0UuNInp1XANBgzUyq9OuqrBlvYEQ==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: boutique
    type: kubernetes.io/dockerconfigjson
