---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: boutique
spec:
  encryptedData:
    .dockerconfigjson: AgBh9W63egi0Eq9elWCTuSLe3L5JUZ5bD/NAWmA13i3woTJq9e2h4ne84OErhQuywQFZ8dezb4xIXP4OarQOEkqalOO+Y8vYC2LpJJstEfeqqqfgxVfK8Kn2aun6+UkeFs/tCJctchCZ5x6ghuyrecVRDMDEvNjMebBoWAy8Ivmcb7+3XNV28OalRd7eosr5uxGcs9jux5geeih4zRHeMXAFksglfsHk9iZ8a1WLxRh4PjNGD/z2/xLrPDIXOKVermJKJd+lWoo6qfNZ8Y1sWh1zjHnls7dRsamFiLsoF9fThafwp6XXtl9XkY+9zFpP/x1lmyVKgCeYZGQsjuYgKGWWIX01eKoDMGuhGbx3l7I/k0Bmob5FndK+di9Ua6PKUvT2MeTF4+iUqcrnWW9nPi132SbVOjJs1m41X/HduUNeyXl1VfShtlYMpPeWVJFZSzpaHGJnqbTfFEnDtSiSdtDYziSTYkJCCO1N38KoE1pQbdYsn2cooQnR/EAobbI89ldzwWw9c4fyhIpsDAN7A//roMS19ZKjlbTNAABdb+FtMKg28BkXE0/AVuhr4aZdONTGTw9hEGB4fX5O5ggiucTrYRNba7P4qFWea2UKhcr38INyzmS6Z6PcwuKVoSSNEQzI8A0sXyckRmz4JKUI2lVPL41Pd39hM+KDpVrUF9glnFzhFvJZtABC18UMSLcrks6sB2SrrtysUiBwNMoH7P/yFy/g65fyXheDwCluC0q6qivXQrssy1aBQWOavHBM2lDnwsctb4I8BA5aAHSHDVQnQZwLJcvzJYeKKAxDjs37wyNwXZqyAcUUvRtvRYf/cPSIMEJnhDITCfX1BJ5VllLfNjhAMyZoist3Y69vjdqvpcBl9Xw/ZCf3NJ0h2h6ue1Cezg19ihmIppCTxUxZQzoowwMJSWm9c8gm3U8F2EbLZQDttA==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: boutique
    type: kubernetes.io/dockerconfigjson
