---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: boutique
spec:
  encryptedData:
    .dockerconfigjson: AgDFrXOeBrMELVTor0EweRtEDpPDNvvnjsDUSp4HQVKuBm9IrQillXgM13I65UDU0s3t6qCrX8Xxd+QU6xWcAsQxdbyvGvW63pkUU/mP/8XLfcSwA2R9rtkIhGf0l7QwzcD4Y1iDoTMvYMnDd31b+Oi+juUcGZDmFiMYT4ArJ70abry+vQn48hFEj88D84IGOJMbsOuVga3NnmemGBNqYCy7i0WqaYJX/rBbIq0tDb1+mHZ2PLzsTASap68MoKhmGLa0+tcSbo97XuSLQLvngu4vUf4qdYFS9oY2YIumcwsJrWhO6ZevEPbWFtDLnZB6npW+H6hgXs8morf8z0I12cdtjPySAIbmapnLJAf6TmpKt3rT9AOrnwwdus+yULspx3AHHCVAvmA2Jxib6WN7cRztJJHSZUO9aMSXxA3MAfXXF+Rr6EXvP4FQnNDxi9kJA1NeTekhUCJbVcviFQMpUONVdFFXRY7ydqAqwIAHZHwnd0OeIP5m8djL415XDkiWD2IwQNFsu4+a+UNY9I9Zjy85lmPB9S0ZWvNxJHmpCwSwgLaftDesv3K9b50vWVIlhDnWvSG/U/+vnp6ouFYOpHzVe0pl3kMsW0ncNdH6LccK7dtXmfOe4i8d+gb5nua9TUqQ39qJVxshq5UGIRGCqXmmh8k1FBApdneEthb9Fi7JfHYQVh/x67MZqvd1jzLAPS+3nhOt54ldXzIE9LCIiaKcB7cKa/p9SldVdj480kmQFVC4SACWHzDv3Bl2Epl5WaLcQB3n6ZEygQ2quzkf/o5II+JNQAeNKya6Fu1DO4ZLc6TPvxRjeOSpjJigUDuJj8NIxm5ZShyrkZVCs3nTwpwoaacXZhk2kIa7XoPIvQhwKEBDf9BCMggMpB367Pj7WONtlTD9NaavLJGUg78Vs4yThpmmI3mFYHvmJMPDs4gh0Mb+Zg==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: boutique
    type: kubernetes.io/dockerconfigjson
