apiVersion: batch/v1
kind: CronJob
metadata:
  name: ai-trainer-cronjob
  namespace: boutique
spec:
  schedule: "0 2 * * * "
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ai-trainer
            image: hmdat1706/ai-prophet:27a153c533e9c55cfc6c6ec248d906299ac53e41
            imagePullPolicy: Always
            command: ["python", "ai_trainer.py"]
            envFrom:
              - configMapRef:
                  name: ai-scaler-config
            volumeMounts:
            - name: shared-mlflow-storage
              mountPath: /mlflow/artifacts
          restartPolicy: OnFailure
          volumes:
          - name: shared-mlflow-storage
            hostPath:
              path: /tmp/mlflow-artifacts
              type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-server
  namespace: boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-server
  template:
    metadata:
      labels:
        app: ai-server
    spec:
      containers:
      - name: ai-server
        image: hmdat1706/ai-prophet:27a153c533e9c55cfc6c6ec248d906299ac53e41
        imagePullPolicy: Always
        command: ["uvicorn", "ai_server:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: ai-scaler-config
        volumeMounts:
        - name: shared-mlflow-storage
          mountPath: /mlflow/artifacts
      volumes:
      - name: shared-mlflow-storage
        hostPath:
          path: /tmp/mlflow-artifacts
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: ai-server-service
  namespace: boutique
spec:
  ports:
  - port: 8000
    targetPort: 8000
    name: http-api
  selector:
    app: ai-server
