---
# ==========================================================
# 1. DAILY DATA INGESTION JOB (Runs at 02:00 AM Daily)
# ==========================================================
apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-ingestion-cronjob
  namespace: boutique
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: data-ingestion
            image: hmdat1706/ai-prophet:latest 
            imagePullPolicy: Always
            command: ["python", "data_ingestion.py"]
            envFrom:
              - configMapRef:
                  name: ai-scaler-config
            volumeMounts:
            - name: shared-mlflow-storage
              mountPath: /mlflow/artifacts
          restartPolicy: OnFailure
          volumes:
          - name: shared-mlflow-storage
            persistentVolumeClaim:
              claimName: mlflow-storage-pvc
---
# ==========================================================
# 2. WEEKLY MODEL RETRAINING JOB (Runs at 02:00 AM every Monday)
# ==========================================================
apiVersion: batch/v1
kind: CronJob
metadata:
  name: model-retrain-cronjob
  namespace: boutique
spec:
  schedule: "0 2 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: model-retrain
            image: hmdat1706/ai-prophet:latest 
            imagePullPolicy: Always
            command: ["python", "model_retrain.py"]
            envFrom:
              - configMapRef:
                  name: ai-scaler-config
            volumeMounts:
            - name: shared-mlflow-storage
              mountPath: /mlflow/artifacts
          restartPolicy: OnFailure
          volumes:
          - name: shared-mlflow-storage
            persistentVolumeClaim:
              claimName: mlflow-storage-pvc
