---
# SSH Connection
ansible_user: somt
ansible_ssh_private_key_file: ~/.ssh/id_rsa

# K3s Configuration
k3s_version: "v1.33.1+k3s1"
kubeseal_version: "0.26.2"

# ArgoCD App-of-Apps manifest path
argocd_app_manifest: "../argocd/apps-app.yaml"

# Sealed Secrets namespaces
sealed_secret_namespaces:
  - boutique
  - monitoring

# GHCR Configuration
ghcr_username: "hmdat-1706"
