[master]
# Đổi thành IP máy ảo 8GB của ông
192.168.3.134 ansible_user=somt ansible_ssh_private_key_file=~/.ssh/id_rsa

[worker]
# Đổi thành IP máy ảo 2GB của ông
192.168.3.136 ansible_user=somt ansible_ssh_private_key_file=~/.ssh/id_rsa