apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Định nghĩa các miếng vá (Patch) cho môi trường Production
# Sắp tới (Hạng mục 3) mình sẽ thêm Patch thay thế Deployment bằng Rollout ở đây.
