name: CI for AI Prophet Scaler

on:
  push:
    paths:
      - 'apps/ai-scaler/**'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1. Bật công cụ Buildx (Bắt buộc để xài Cache)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 2. Đăng nhập Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build & Push kết hợp siêu Cache của GitHub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/ai-scaler
          push: true
          tags: hmdat1706/ai-prophet:${{ github.sha }}
          # Kéo Cache từ lần chạy trước xuống
          cache-from: type=gha
          # Lưu Cache của lần chạy này lại cho lần sau
          cache-to: type=gha,mode=max

      # 4. Cập nhật Manifest cho ArgoCD (Giữ nguyên)
      - name: Update Manifest Tag (GitOps)
        run: |
          sed -i "s|image: hmdat1706/ai-prophet:.*|image: hmdat1706/ai-prophet:${{ github.sha }}|g" apps/ai-scaler/ai-scaler-architecture.yaml
          
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          git add apps/ai-scaler/ai-scaler-architecture.yaml
          git commit -m "chore: update ai-prophet image tag to ${{ github.sha }}"
          git push
