---
name: Audit CI (Security & Manifests)

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  quality-checks:
    name: Lint & Quality Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Lint Python (Flake8)
        run: |
          pip install flake8
          # Quét lỗi cú pháp nghiêm trọng
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Lint YAML Files
        run: |
          sudo apt-get install yamllint -y
          yamllint -f standard .

  k8s-manifest-validation:
    name: Validate Kubernetes Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Kubeconform
        run: |
          wget https://github.com/yannh/kubeconform/releases/download/v0.6.4/kubeconform-linux-amd64.tar.gz
          tar -xf kubeconform-linux-amd64.tar.gz
          sudo mv kubeconform /usr/local/bin/

      - name: Run Kubeconform
        run: |
          find apps/ infra/ -type f -name "*.yaml" ! -path "*/prophet_model/*" ! -path "*/ansible/*" ! -name "values.yaml" ! -name "kustomization.yaml" ! -name "*-patch.yaml" | xargs kubeconform -summary -strict -ignore-missing-schemas

  security-scanning:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy Vulnerability Scanner (Filesystem)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "table"
          severity: "CRITICAL,HIGH"
          ignore-unfixed: true
          exit-code: "1"
