---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: boutique
spec:
  encryptedData:
    .dockerconfigjson: AgCP8HuGJNNSYNk43uTdiROXxgIzwICSWRU1PfsY3u/7ktxjeb8goUdT4ztVg3S4jCDqDZohQ95gE2zPVLY13lYPkh8E0c/M3bv+Fsvk1ElDIUV5h1mVkEwmWx4B/7AvY8V09p+664c7gBpQs8/MdpYSZgZUvgr0TtiaWXdJa1VQQQp8sdUgb38i4v63OtAsxUjdntxu8ZH+ySdV0ENNXSDts43YwbPFKQUrOZXrAw136EZvU3QZ4Y0sV4bSPro/JAl6T8IBIzjzSNXVncZEzN+TwEeJoUpoUQDUTu3srzNeiqWDKF5BA7aRYWzunds7oTzriCBWb9/wG2xUE0fQwmFyQKtrE/5113REiOeCA1Yb8edAX9sAprzVsTbMl0ROttWFo0fjc4W4HfWeZtlTipcPei5R3rFQZf2yPyJV1pEywPHTbvbsv31lG9nnKx2YzQb8qYFaGuP9aVyO0Qy109KjXTD/8EEZ3G3cMSjEsU96miLtP0sQejSF5khmgulrFuxlLcQi/RJDbUYfpsmdPmltmoGMRKSYih0toOLzYo/afkQfSNB7j1QNhLa+Dsk94ofqnjKwq2iU6ITyEi1JpRPYWBLn/bb8KlN6FIhQrmJBC1RKgtk0tBwybPG1Ftz3ad+gNfu3/zWTROMB/XA0we9b0A4MomQRn99EmyiR35J+FWIIytZduM9tazmW6zf3Qz8GCzK9ADL/u/lw5Hcmf6nHuatNOQ9No+xXcoyevYGXVENG0900njH67cGveiqbxxPxjakzxZTlQ6nUBDqTCMe3FbPnibmscLYiIuycE6RN45OU68F/dsJSlb3emz47GNwubY2JnK+Y4EkwL+hC1Heq4P90BoFIMzVaDalTSYCuiKA5ZybkiN8n/jQxARJnUr6DfK0ZBuACMqGZw2eXAbQNxvfy/XlwhYXuKAKQr0J3SaGLBQ==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: boutique
    type: kubernetes.io/dockerconfigjson
