---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: boutique
spec:
  encryptedData:
    .dockerconfigjson: AgBuXD9gE1OVm8IaTh334fpwgiUrpCQGiVHaB2712j4698C/qBknvm5n76pwqN1XHNrVsANpKHF7OZVZFYYnqTSMfcdwhC0ogUWGqPFEDB3LRuA4CmGWAmYajZgU4y3QukuB2HckSTTIn6tIglD+ES3YdazwhN9lm9LcXMBf63Lmr34ijGj5BlzGDt1AG6ZNlQ44mDvLE2zlIAylbWdR5H4PIkOFSeYst/oK5qLzqJP5uLYgktLmBN9+3XW1RzylEXrTlwjO2EanRx39g8hK+URvzWeQRdlODYeLsDyGhoqAnXdZl10N4Ia4pIr9Rtb8S3QViIP2aqyyrPbWxnOF8QXF4Kl6Ucrqj3PyhcnmqeOrhEdye8aw+mvuXumwrhbbqObhrv55q1b/A1nRDKhfPhbjXM1mctgyZLvfXYMi7jbbOx7fCq7ZY5VBXDddEo4ZMly4yACPs2PUipoOSNoSPiZBRTToMjDbkP7Cx3DQEWqjxN0pJytR+/v3NzN5Cw1sAnARC4vnjrzVu6NBh8DeSvsVDUau9Fx/2dG1QUe8R1eMNhvRm6Ti99g9J8VRy0rZ4TRBAtGaSRwCuxocVNYAra3Gh4EWOXWrHymLuwDrrjhyWs8+tJEDn5/JCz4mt8sJunLrVn+OECALYkB/V0QPAD72tO7KqKzlGs9xlgsZ2oG5LKRQ54WGC2hyqeato+3k8S3LksRKT+Q1vkYmuNCtAYZpnWQ00H7kmZuwLlm47YPJwiZjzEbPcWCW7ScB8Ux7Yb6uCkuP+MTL9Y3jghHfLEUJ/KhAdUs2HJrsE2l2W20OrkSMki3avzS3ACXprdfAfOnAgb60ZcUd+0y804z92WJIY+m220MIzwZahf9D29wESie8eacvmADkD5MDV6z+8AAxiLO7XgA1V9OikCwfJwj0ilwXGDkN0Qzzu35vySkXa4gqSw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: boutique
    type: kubernetes.io/dockerconfigjson
