---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: boutique
spec:
  encryptedData:
    .dockerconfigjson: AgAfupf857HvFExEqiFWzY3WuA7ud6bRNIJMy8H9HPubInsjYhWwT/Xh90JE8iC1yR4wIem0xc0jigK/fJhWEVLK/+51yC16FX5MAOawJkDh7ru/2I+wOzp5BxV/L/TD2vW7wucilhTVu2DlbICsPPjmC3QJGKjTGXzb1pt3VR1kS3kPRQcBUv5/n5WHjgPqbDdOX3FeZdrS3ePA9pB/9Swr+C+9e/5kTTWgjuTDWVyAOw8vwh5KMKwQlKHTQGR9Lvijj0QDtOSQJACZ07uijWp8RwA1I4SaaS0GCOhB/Kg6NY7Lcq3AAG8sAdJlkDZLzUDLXE2fHYXZLNdDGAruXoyOIChuHVUvi0M6WXfNSYcY4h5HjuSddaC8FDfkxAupUfYjV3MBrzAGKmjldxmrn7ZAi6qgxes9cGt1z/4b2uBDoDBQuTkbcLsfZWXb4tH9qAvQfroHvxr/nsSofB46mP3FNwfyAH0XDfKak2Cb0hILA/GdxgQZRheOCfE7Juaq9RT2dCbk4hrkWcKjMtMhnXZR5JDDe6lCqC9F9OdY9Nn57MkPJT68PtnRWJxrGVP75mIiW4U05QtbuVZ6Kygzcr9pfismzEJqZgzsWp1rYUqaJxY40r/4DvoToE+9fE5L9obmT1TtUGuFQ1zrCy+4Ok04vm2K4faBxgtreLu4OgSXQ6BtChwd19OKIxu8aESzbqscjlrFQaYYeNsq7QAedgW5LnyH0OGzHDugmvJzfCF/DMNhylbzqYV9TC+y7SldI8Isy3I+3InI1DBa0WEMYuzH17kkMMiY/conwslyz8JQEKqSvSIXmnL6MjLFx9ZSR/Hy6yq58GVKFduokEQHOVL/lyl9Lzsv7wkRafs8KieAkIZe/L3QulgfiaRaTlH0EhSBE4yRVr/LTQ/4aUkVCoLrumSOXeFwafqex6v/+UcXHki/Zw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: boutique
    type: kubernetes.io/dockerconfigjson
